
title: Nikunj Dobariya
name: Nikunj Dobariya
email: ndobariya219@gmail.com
description: Nikunj Dobariya's portfolio website | Solution Architect | Assoc Manager @ Accenture Australia.
baseurl: /
url: http://ndobariya219.github.io
twitter: nikunjdobariya
github:  ndobariya219
linkedin: nikunjdobariya
google_analytics: G-V1KBRX7BY7
resume_url: http://ndobariya219.github.io/docs/nikunj_dobariya.pdf

# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:title.html
theme: minima
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
